### ISSUE TITLE
Sparse matching version?

### ISSUE THREAD

**Issue by vkartha** [jsilve24/RcppHungarian#1]
Hi, thank you for writing a useful wrapper to help with this matching implementation in R. I was wondering, do you think it would be easy to have a sparse version of this, where, certain distances in the input rectangular matrix can be ignored (say if they are not feasible matches), which would in theory, drastically speed up the computation / match determination process? This does not scale for very large matrices, and I have to work with one currently to solve a global matching problem.

**Comment by jsilve24** [comment]
sorry for the long delay. Yes this could be possible but is not a feature I would plan to implement in the near future.
